### ISSUE TITLE
Searching RAM will not go away

### ISSUE THREAD

**Issue by jme2712** [WerWolv/EdiZon#58]
I see [HEAP + 0x.....], greyed out behind the subject pop up, but it will not disappear for me to meddle with the addresses found. Is this a bug? Only way to get out is either home or the plus button, which resets Edizon. This is on the latest build.

**Comment by WerWolv** [comment]
This should have been fixed in v3.0.1. It's definitely not there anymore now in my WIP version

**Comment by painiax** [comment]
Still have the problem on 3.0.1. "Truncated" message appears and searching never goes away

**Comment by dmplays** [comment]
I have the same problem like painiax. Only when I search for s64 or u64 Integers the Banner goas away. 
I got this problem when I updatet to 8.0.0 I dont know if it is a bug in the cfw or in edizon.

The search should be fine, in the background I can see the Ram-Adresses it found. But the focus is on the "Searching Ram ...".

When I search for u64 or s64 everything works fine.

Can you invastigate this issue?

Best regards
Daniel

**Comment by BASgamer** [comment]
Switch 7.0.1
AMS 0.8.9
Edizon 3.0.1

when doing a u8 scan in "i am setsuna" itll say too many results but the ram scanning window wont go away

Switch 7.0.1
AMS 0.8.9
Edizon 3.0

downgrading to edizone 3.0 fixed it for me same as the last posters edit

**Comment by WerWolv** [comment]
Try using a bigger search type for now. There are very very few cases where u8s are actually needed. Upgrading to the nightlies would also fix the issue http://bsnx.lavatech.top/edizon/

**Comment by BASgamer** [comment]
inventory only use 2 bits a lot of the time so bigger searchers werent a possibilty for me, but thank you ill try a nightly when i get some time
